ktor:
  application:
    modules:
      - ru.clevertec.ApplicationKt.module
  deployment:
    port: 8091
database:
  url: jdbc:postgresql://localhost:5433/user-api
  user: admin
  password: pass
  driver: org.postgresql.Driver
  maxPoolSize: 10
liquibase:
  changelog: db/changelog/db.changelog-master.yaml
jwt:
  issuer: "library-service"
  secret: "your-secret-key-change-in-production"
